version: '3.4'

services:
  my_service_name:
    image: foo/bar:version
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: replicated
      replicas: 1
      restart_policy:
        conditions: any
      update_config:
        parallelism: 1
        delay: 60s
        order: start-first
        failure_action: rollback
    healthcheck:
      test: curl -f http://localhost:8080 || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
 
networks:
  mynetwork:
    external: true
